import { test } from "node:test";
import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
test("the public CLI produces Mat Cloud App as a static website with its original inputs", async () => {
  const root = ".gen/mleweb/www/";
  const html = await readFile(root + "index.html", "utf8");
  assert.match(html, /<title>Mat Cloud App<\/title>/);
  assert.match(html, /Welcome in my Cloud/);
  assert.match(html, /Retro_Mario_in_3D_flavor_by_cezkid.gif/);
  assert.match(html, /https:\/\/blog.mlefree.com\/p\/about.html/);
  assert.match(html, /https:\/\/github.com\/ofidj/);
  assert.match(html, /https:\/\/twitter.com\/mat_cloud/);
  assert.match(html, /hello@mlefree.com/);
  assert.equal((await readFile(root + "CNAME", "utf8")).trim(), "mlefree.com");
  const js = await readFile(root + "main.js", "utf8");
  assert.doesNotMatch(js, /fetch\("\/api\//);
  assert.match(js, /Create an account/);
  assert.match(js, /Export my app data/);
  assert.match(js, /Leave this app/);
  assert.ok(!(await readdir(root)).some((name) => name.startsWith(".env")));
});
